//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeta_v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALIFICACION
    {
        public decimal ID_CALIFICACION { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public string ID_USUARIO { get; set; }
        public Nullable<int> PUNTUACION { get; set; }
        public string TITULO_CALIFICACION { get; set; }
        public string TEXTO_CALIFICACION { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
