//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeta_v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANCELACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CANCELACION()
        {
            this.CHECKOUT1 = new HashSet<CHECKOUT>();
            this.ESTADO_CANCELACION = new HashSet<ESTADO_CANCELACION>();
        }
    
        public decimal ID_CANCELACION { get; set; }
        public decimal ID_CHECKOUT { get; set; }
        public Nullable<System.DateTime> FECHA_CANCELACION { get; set; }
        public Nullable<System.DateTime> HORA_CANCELACION { get; set; }
        public string RAZON_CANCELACION { get; set; }
    
        public virtual CHECKOUT CHECKOUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECKOUT> CHECKOUT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTADO_CANCELACION> ESTADO_CANCELACION { get; set; }
    }
}
