//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeta_v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARACTERISTICAS
    {
        public decimal ID_CARACTERISTICA { get; set; }
        public decimal ID_CATEGORIA { get; set; }
        public string NOMBRE_CARACTERISTICA { get; set; }
    
        public virtual CATEGORIA_PRODUCTO CATEGORIA_PRODUCTO { get; set; }
    }
}
