//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeta_v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARACTERISTICAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARACTERISTICAS()
        {
            this.CARACTERISTICA_PRODUCTO = new HashSet<CARACTERISTICA_PRODUCTO>();
        }
    
        public decimal ID_CARACTERISTICA { get; set; }
        public decimal ID_CATEGORIA { get; set; }
        public string NOMBRE_CARACTERISTICA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARACTERISTICA_PRODUCTO> CARACTERISTICA_PRODUCTO { get; set; }
        public virtual CATEGORIA_PRODUCTO CATEGORIA_PRODUCTO { get; set; }
    }
}
