//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeta_v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIA_SUPERIOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORIA_SUPERIOR()
        {
            this.CATEGORIA_PRODUCTO = new HashSet<CATEGORIA_PRODUCTO>();
        }
    
        public decimal ID_CATEGORIA_SUPERIOR { get; set; }
        public string NOMBRE_CATEGORIA_SUPERIOR { get; set; }
        public string DESCRIPCION_CATEGORIA_SUPERIOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATEGORIA_PRODUCTO> CATEGORIA_PRODUCTO { get; set; }
    }
}
