//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeta_v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_CANCELACION
    {
        public decimal ID_ESTADO_CANCELACION { get; set; }
        public decimal ID_CANCELACION { get; set; }
        public string ESTADO_CANCELACION1 { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZACION_CANCELACION { get; set; }
        public string RAZON_ESTADO_CANCELACION { get; set; }
    
        public virtual CANCELACION CANCELACION { get; set; }
    }
}
