//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeta_v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_RECLAMO
    {
        public decimal ID_ESTADO_RECLAMO { get; set; }
        public decimal ID_RECLAMO { get; set; }
        public string DESCRIPCION_ESTADO { get; set; }
        public string RAZON_ESTADO { get; set; }
    
        public virtual RECLAMO RECLAMO { get; set; }
    }
}
