//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeta_v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_DELIVERY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESTADO_DELIVERY()
        {
            this.CHECKOUT = new HashSet<CHECKOUT>();
            this.PAGOS_DELIVERY1 = new HashSet<PAGOS_DELIVERY>();
        }
    
        public decimal ID_ESTADO_DELIVERY { get; set; }
        public Nullable<decimal> ID_PAGOS_DELIVERY { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZACION_DELIVERY { get; set; }
        public string ESTADO_DELIVERY1 { get; set; }
        public Nullable<System.DateTime> HORA_ACTUALIZACION_DELIVERY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECKOUT> CHECKOUT { get; set; }
        public virtual PAGOS_DELIVERY PAGOS_DELIVERY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGOS_DELIVERY> PAGOS_DELIVERY1 { get; set; }
    }
}
