//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeta_v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA_VENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURA_VENTA()
        {
            this.CHECKOUT = new HashSet<CHECKOUT>();
            this.PRODUCTO_FACTURA = new HashSet<PRODUCTO_FACTURA>();
        }
    
        public decimal ID_FACTURA { get; set; }
        public Nullable<decimal> ID_CHECKOUT { get; set; }
        public string NRO_FACTURA { get; set; }
        public Nullable<System.DateTime> FECHA_FACTURA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECKOUT> CHECKOUT { get; set; }
        public virtual CHECKOUT CHECKOUT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO_FACTURA> PRODUCTO_FACTURA { get; set; }
    }
}
