//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeta_v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOTO_PRODUCTO
    {
        public decimal ID_FOTO { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public string LINK_FOTO { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
