//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeta_v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGOS_BANCARD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAGOS_BANCARD()
        {
            this.RECIBO_BANCARD = new HashSet<RECIBO_BANCARD>();
        }
    
        public decimal ID_PAGO_BANCARD { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO_BANCARD { get; set; }
        public Nullable<System.DateTime> HORA_PAGO_BANCARD { get; set; }
        public string FACTURA_PAGO_BANCARD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECIBO_BANCARD> RECIBO_BANCARD { get; set; }
    }
}
