//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeta_v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_FACTURA
    {
        public decimal ID_PRODUCTO_FACTURA { get; set; }
        public decimal ID_FACTURA { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public Nullable<decimal> PRECIO_PRODUCTO_FACTURA { get; set; }
        public Nullable<int> CANTIDAD_PRODUCTO_FACTURADO { get; set; }
    
        public virtual FACTURA_VENTA FACTURA_VENTA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
