//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeta_v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.CATEGORIA = new HashSet<CATEGORIA>();
            this.FOTO = new HashSet<FOTO>();
        }
    
        public decimal ID_PRODUCTO { get; set; }
        public Nullable<decimal> ID_USUARIO { get; set; }
        public string NOMRE_PRODUCTO { get; set; }
        public string ESTADO_USO { get; set; }
        public Nullable<System.DateTime> PUBLICACION_PRODUCTO { get; set; }
        public string FACTURA_PRODUCTO { get; set; }
        public string DESCRIPCION_PRODUCTO { get; set; }
        public Nullable<decimal> PRECIO_VENTA { get; set; }
        public Nullable<decimal> PRECIO_PROMOCION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATEGORIA> CATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOTO> FOTO { get; set; }
    }
}
