//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeta_v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIBO_BANCARD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECIBO_BANCARD()
        {
            this.CHECKOUT = new HashSet<CHECKOUT>();
        }
    
        public decimal ID_RECIBO_BANCARD { get; set; }
        public decimal ID_PAGO_BANCARD { get; set; }
        public decimal ID_CHECKOUT { get; set; }
        public Nullable<System.DateTime> FECHA_RECIBO { get; set; }
        public Nullable<System.DateTime> HORA_RECIBO { get; set; }
        public string LINK_RECIBO { get; set; }
        public Nullable<decimal> MONTO_RECIBO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECKOUT> CHECKOUT { get; set; }
        public virtual CHECKOUT CHECKOUT1 { get; set; }
        public virtual PAGOS_BANCARD PAGOS_BANCARD { get; set; }
    }
}
