//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeta_v3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zeta_bdEntities2 : DbContext
    {
        public zeta_bdEntities2()
            : base("name=zeta_bdEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CALIFICACION> CALIFICACION { get; set; }
        public virtual DbSet<CANCELACION> CANCELACION { get; set; }
        public virtual DbSet<CANTIDAD_PRODUCTO> CANTIDAD_PRODUCTO { get; set; }
        public virtual DbSet<CARACTERISTICAS> CARACTERISTICAS { get; set; }
        public virtual DbSet<CARRITO> CARRITO { get; set; }
        public virtual DbSet<CATEGORIA_PRODUCTO> CATEGORIA_PRODUCTO { get; set; }
        public virtual DbSet<CHECKOUT> CHECKOUT { get; set; }
        public virtual DbSet<CIUDAD> CIUDAD { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public virtual DbSet<DIRECION> DIRECION { get; set; }
        public virtual DbSet<ESTADO_CANCELACION> ESTADO_CANCELACION { get; set; }
        public virtual DbSet<ESTADO_DELIVERY> ESTADO_DELIVERY { get; set; }
        public virtual DbSet<ESTADO_RECLAMO> ESTADO_RECLAMO { get; set; }
        public virtual DbSet<FOTO_PRODUCTO> FOTO_PRODUCTO { get; set; }
        public virtual DbSet<GASTO> GASTO { get; set; }
        public virtual DbSet<INGRESO_PRODUCTO> INGRESO_PRODUCTO { get; set; }
        public virtual DbSet<LISTA_DESEOS> LISTA_DESEOS { get; set; }
        public virtual DbSet<PAGOS_BANCARD> PAGOS_BANCARD { get; set; }
        public virtual DbSet<PAGOS_DELIVERY> PAGOS_DELIVERY { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<RECIBO_BANCARD> RECIBO_BANCARD { get; set; }
        public virtual DbSet<RECLAMO> RECLAMO { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
