//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeta_v3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zeta_bdEntities8 : DbContext
    {
        public zeta_bdEntities8()
            : base("name=zeta_bdEntities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<BUSQUEDA> BUSQUEDA { get; set; }
        public virtual DbSet<CALIFICACION> CALIFICACION { get; set; }
        public virtual DbSet<CANCELACION> CANCELACION { get; set; }
        public virtual DbSet<CANTIDAD_PRODUCTO> CANTIDAD_PRODUCTO { get; set; }
        public virtual DbSet<CARACTERISTICA_PRODUCTO> CARACTERISTICA_PRODUCTO { get; set; }
        public virtual DbSet<CARACTERISTICAS> CARACTERISTICAS { get; set; }
        public virtual DbSet<CARRITO> CARRITO { get; set; }
        public virtual DbSet<CATEGORIA_PRODUCTO> CATEGORIA_PRODUCTO { get; set; }
        public virtual DbSet<CHECKOUT> CHECKOUT { get; set; }
        public virtual DbSet<CIUDAD> CIUDAD { get; set; }
        public virtual DbSet<COLOR> COLOR { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public virtual DbSet<DIRECION> DIRECION { get; set; }
        public virtual DbSet<ESTADO_CANCELACION> ESTADO_CANCELACION { get; set; }
        public virtual DbSet<ESTADO_DELIVERY> ESTADO_DELIVERY { get; set; }
        public virtual DbSet<ESTADO_RECLAMO> ESTADO_RECLAMO { get; set; }
        public virtual DbSet<FACTURA_VENTA> FACTURA_VENTA { get; set; }
        public virtual DbSet<FOTO_PRODUCTO> FOTO_PRODUCTO { get; set; }
        public virtual DbSet<GASTO> GASTO { get; set; }
        public virtual DbSet<INGRESO_PRODUCTO> INGRESO_PRODUCTO { get; set; }
        public virtual DbSet<LISTA_DESEOS> LISTA_DESEOS { get; set; }
        public virtual DbSet<LOG> LOG { get; set; }
        public virtual DbSet<PAGOS_BANCARD> PAGOS_BANCARD { get; set; }
        public virtual DbSet<PAGOS_DELIVERY> PAGOS_DELIVERY { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<PRODUCTO_FACTURA> PRODUCTO_FACTURA { get; set; }
        public virtual DbSet<PRODUCTOXCATEGORIA> PRODUCTOXCATEGORIA { get; set; }
        public virtual DbSet<PUBLICACION> PUBLICACION { get; set; }
        public virtual DbSet<RECIBO_BANCARD> RECIBO_BANCARD { get; set; }
        public virtual DbSet<RECLAMO> RECLAMO { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<TAMANO> TAMANO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<VISITA_PRODUCTO> VISITA_PRODUCTO { get; set; }
    }
}
